#############################################################################
# Generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#  Dec 10, 2020 05:42:18 PM CET  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1148x441+375+338
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "denpa-qr-edit"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can45 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 371 -highlightcolor black -insertbackground black \
        -relief ridge -selectbackground blue -selectforeground white \
        -width 262 
    vTcl:DefineAlias "$top.can45" "DanpaCanvas" vTcl:WidgetProc "Toplevel" 1
    canvas $top.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 301 -highlightcolor black -insertbackground black \
        -relief ridge -selectbackground blue -selectforeground white \
        -width 291 
    vTcl:DefineAlias "$top.can46" "QRCanvas" vTcl:WidgetProc "Toplevel" 1
    entry $top.ent48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 156 
    vTcl:DefineAlias "$top.ent48" "NameEntry" vTcl:WidgetProc "Toplevel" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Name 
    vTcl:DefineAlias "$top.lab49" "NameLabel" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo50 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo50" "FaceSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo51 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "HeadSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo52 \
        -font TkTextFont -textvariable antenna -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "AntennaSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo53 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo53" "RegionSelect" vTcl:WidgetProc "Toplevel" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Region 
    vTcl:DefineAlias "$top.lab54" "RegionLabel" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo55 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo55" "GlassesSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo56 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo56" "EyeSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo57 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo57" "SkinSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo58 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo58" "ColorSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo59 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo59" "TCombobox9" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo60 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo60" "DyeSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo61 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo61" "CheekSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo62 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo62" "HairSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo63 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo63" "NoseSelect" vTcl:WidgetProc "Toplevel" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu64 \
        -takefocus {} -text {Scan from Camera} 
    vTcl:DefineAlias "$top.tBu64" "ScanButton" vTcl:WidgetProc "Toplevel" 1
    button $top.but66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Change ID} 
    vTcl:DefineAlias "$top.but66" "IDButton" vTcl:WidgetProc "Toplevel" 1
    ttk::combobox $top.tCo67 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo67" "GameSelect" vTcl:WidgetProc "Toplevel" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {This QR Code is for } 
    vTcl:DefineAlias "$top.lab68" "GameLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text ID: 
    vTcl:DefineAlias "$top.lab69" "IDLabel" vTcl:WidgetProc "Toplevel" 1
    text $top.tex70 \
        -background white -font TkTextFont -foreground black \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 106 -wrap word 
    $top.tex70 configure -font "TkTextFont"
    $top.tex70 insert end text
    vTcl:DefineAlias "$top.tex70" "IDText" vTcl:WidgetProc "Toplevel" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Antenna 
    vTcl:DefineAlias "$top.lab46" "AntennaLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Head Shape} 
    vTcl:DefineAlias "$top.lab47" "HeadLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Facial Structure} 
    vTcl:DefineAlias "$top.lab48" "FaceShape" vTcl:WidgetProc "Toplevel" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Cheek Decals} 
    vTcl:DefineAlias "$top.lab50" "CheekLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Haircut 
    vTcl:DefineAlias "$top.lab51" "HairLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Nose 
    vTcl:DefineAlias "$top.lab52" "NoseLabel" vTcl:WidgetProc "Toplevel" 1
    spinbox $top.spi53 \
        -activebackground #f9f9f9 -background white -font TkDefaultFont \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground blue -selectforeground white -textvariable spinbox \
        -to 100.0 
    vTcl:DefineAlias "$top.spi53" "AttrSpinbox" vTcl:WidgetProc "Toplevel" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Attributes 
    vTcl:DefineAlias "$top.lab55" "AttrLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab56 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Glasses 
    vTcl:DefineAlias "$top.lab56" "GlassesLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab57 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Eye Type} 
    vTcl:DefineAlias "$top.lab57" "EyesLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab58 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Skin Tone} 
    vTcl:DefineAlias "$top.lab58" "SkinLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab59 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Hair Dye} 
    vTcl:DefineAlias "$top.lab59" "DyeLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab60 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Body Color} 
    vTcl:DefineAlias "$top.lab60" "ColorLabel" vTcl:WidgetProc "Toplevel" 1
    label $top.lab61 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Mouth 
    vTcl:DefineAlias "$top.lab61" "MouthLabel" vTcl:WidgetProc "Toplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can45 \
        -in $top -x 320 -y 67 -width 262 -relwidth 0 -height 352 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can46 \
        -in $top -x 590 -y 110 -width 290 -relwidth 0 -height 286 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 360 -y 38 -width 156 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 309 -y 38 -width 49 -relwidth 0 -height 29 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo50 \
        -in $top -x 100 -y 180 -width 178 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 100 -y 130 -width 178 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 100 -y 76 -width 180 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo53 \
        -in $top -x 610 -y 80 -width 97 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 620 -y 60 -width 48 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo55 \
        -in $top -x 920 -y 80 -anchor nw -bordermode ignore 
    place $top.tCo56 \
        -in $top -x 920 -y 140 -anchor nw -bordermode ignore 
    place $top.tCo57 \
        -in $top -x 920 -y 190 -anchor nw -bordermode ignore 
    place $top.tCo58 \
        -in $top -x 920 -y 300 -anchor nw -bordermode ignore 
    place $top.tCo59 \
        -in $top -x 920 -y 350 -anchor nw -bordermode ignore 
    place $top.tCo60 \
        -in $top -x 920 -y 240 -anchor nw -bordermode ignore 
    place $top.tCo61 \
        -in $top -x 100 -y 240 -anchor nw -bordermode ignore 
    place $top.tCo62 \
        -in $top -x 100 -y 300 -anchor nw -bordermode ignore 
    place $top.tCo63 \
        -in $top -x 100 -y 350 -anchor nw -bordermode ignore 
    place $top.tBu64 \
        -in $top -x 30 -y 10 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 800 -y 80 -width 81 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo67 \
        -in $top -x 1000 -y 20 -width 127 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 860 -y 20 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 610 -y 400 -anchor nw -bordermode ignore 
    place $top.tex70 \
        -in $top -x 640 -y 400 -width 106 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 100 -y 60 -width 58 -relwidth 0 -height 11 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 100 -y 110 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 100 -y 160 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 100 -y 220 -width 92 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 100 -y 280 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 100 -y 330 -anchor nw -bordermode ignore 
    place $top.spi53 \
        -in $top -x 180 -y 390 -width 88 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 100 -y 390 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 920 -y 60 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 920 -y 120 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 920 -y 170 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 920 -y 220 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 920 -y 280 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 920 -y 330 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

